### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './plugins/

### ISSUE THREAD

**Issue by DanielMSchmidt** [cschuller/yakjs#65]
Hi there,

Thank you for this great project, it really looks like the kind of tool we want to build our integration tests around. Unfortunately when I install it and start it I get this error:

```sh
$ yakjs
fs.js:928
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './plugins/'
    at Object.fs.readdirSync (fs.js:928:18)
    at getAvailablePluginFilenames (/Users/danielschmidt/.npm/lib/node_modules/yakjs/src/plugin/pluginProvider.js:60:28)
    at PluginProvider.loadPlugins (/Users/danielschmidt/.npm/lib/node_modules/yakjs/src/plugin/pluginProvider.js:33:21)
    at PluginManager.loadPlugins (/Users/danielschmidt/.npm/lib/node_modules/yakjs/src/plugin/pluginManager.js:33:34)
    at Object.<anonymous> (/Users/danielschmidt/.npm/lib/node_modules/yakjs/src/yakServerState.js:17:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

My system is OSX 10.13.3 with node 9.8.0

**Comment by DanielMSchmidt** [comment]
That did work 👍

**Comment by cschuller** [comment]
* Problem can also be be reproduced on Ubuntu LTS. 
* Works on windows. 
* Work-around: Use `node yakjs.js` in `node_modules/yakjs/` folder.

Will be fixed with the next version 3.1.0

**Comment by DanielMSchmidt** [comment]
Wow, that was fast, thank you 👍

**Comment by cschuller** [comment]
I am not always that responsive ;-) Was just working on the new "snapshot" feature and getting version 3.1.0 ready.
